# Generated by Django 5.2 on 2025-08-28 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jelibit', '0002_customuser_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
    ]
