# Generated by Django 5.2 on 2025-09-03 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jelibit', '0003_remove_customuser_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverificationcode',
            old_name='code',
            new_name='otp',
        ),
    ]
